-- Business profiles table
CREATE TABLE business_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    business_name TEXT NOT NULL,
    business_type TEXT NOT NULL,
    business_address TEXT NOT NULL,
    business_constituency TEXT NOT NULL,
    business_county TEXT NOT NULL,
    contact_person TEXT NOT NULL,
    contact_email TEXT,
    contact_phone TEXT NOT NULL,
    number_of_employees INTEGER NOT NULL,
    business_description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Business waste details table
CREATE TABLE business_waste_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_profile_id BIGINT REFERENCES business_profiles(id) NOT NULL,
    waste_generated_kg_per_week NUMERIC NOT NULL,
    waste_types TEXT[] NOT NULL,
    current_disposal_method TEXT,
    sorting_capability BOOLEAN DEFAULT FALSE,
    recycling_interest BOOLEAN DEFAULT FALSE,
    collection_frequency_preference TEXT,
    special_requirements TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Business types reference table
CREATE TABLE business_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert common business types
INSERT INTO business_types (type_name, description) VALUES
('Restaurant', 'Food service establishments'),
('Retail Store', 'Shops and retail businesses'),
('Office', 'Corporate and professional offices'),
('Hotel', 'Accommodation and hospitality'),
('Manufacturing', 'Production and manufacturing facilities'),
('Healthcare', 'Hospitals, clinics, and healthcare facilities'),
('Educational Institution', 'Schools, colleges, and universities'),
('Entertainment Venue', 'Theaters, clubs, and entertainment facilities'),
('Warehouse', 'Storage and distribution facilities'),
('Shopping Mall', 'Large retail complexes'),
('Apartment Complex', 'Residential apartment buildings'),
('Construction', 'Construction companies and sites'),
('Technology', 'IT and technology companies'),
('Food Processing', 'Food production and processing facilities'),
('Agriculture', 'Farms and agricultural businesses');

-- Create indexes for better query performance
CREATE INDEX business_profiles_user_id_idx ON business_profiles(user_id);
CREATE INDEX business_waste_details_profile_id_idx ON business_waste_details(business_profile_id);
